chore: peer-discovery, connection manager and protokol-connection
protokol/nft-plugins pull request #178
Opened 2020-10-14 10:00 UTC by KovacZan

## Summary

### What changes are being made?
- Updated peer-discovery to work with the latest core changes
- removed nft-connection and guardian-connection, combined them into protokol-connection
- updated connection-manager to work with protokol-connection

### Why are these changes necessary?
- peer-discovery: to work with lates core
- protokol-connection: less redundant code

## Checklist

- [ ] Documentation _(if necessary)_
- [x] Tests _(if necessary)_
- [x] Ready to be merged

2020-10-14 12:09 UTC, kristjank approved these changes

2020-10-14 12:13 UTC, amacar requested changes
I will fix some tests to keep up the coverage to 100%.

2020-10-14 12:27 UTC, KovacZan commented on packages/client/__tests__/connection/connection-manager.test.ts
> +const nock = require("nock");
Current ts settings throw a warning if I leave it as a import

2020-10-15 08:31 UTC, amacar approved these changes

2020-10-15 09:56 UTC, merged